(rule
 (targets orders.ml orders.mli common.ml common.mli numbers.ml numbers.mli drut_runtime.ml)
 (deps
  (source_tree ../fixtures/orders)
  %{exe:../gen/gen.exe})
 (action
  (run %{exe:../gen/gen.exe} ../fixtures/orders . ocaml js)))

(library
 (name generated_fixtures_js)
 (libraries cyrograf yojson)
 (modules orders common numbers drut_runtime))